name: mes_ams_lab7
description: A task management application using a mock api (https://jsonplaceholder.typicode.com/guide)
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^1.3.0
  intl: ^0.17.0
  posts_api:
    path: packages/posts_api
  posts_repository:
    path: packages/posts_repository

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
